# Generated by Django 5.2.4 on 2025-07-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiveGameStore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Stock',
            new_name='stock',
        ),
    ]
