# Generated by Django 5.2.4 on 2025-08-05 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiveGameStore', '0007_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='productid',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='userid',
            new_name='user',
        ),
    ]
