# Generated by Django 5.2.4 on 2025-08-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiveGameStore', '0009_remove_order_product_order_created_at_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
