# Generated by Django 5.2.4 on 2025-08-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveGameStore', '0013_alter_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
