# Generated by Django 5.2.4 on 2025-08-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveGameStore', '0015_alter_order_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('PC Case', 'PC Case'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Monitor', 'Monitor'), ('Motherboard', 'Motherboard'), ('Graphics Card', 'Graphics Card')], max_length=200),
        ),
    ]
