# Generated by Django 5.2.4 on 2025-08-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveGameStore', '0016_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
