# Generated by Django 5.2.4 on 2025-08-08 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiveGameStore', '0019_remove_product_slug_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
